---
name: "Super-Linter slim"
author: "step-security"
description: "Super-linter is a ready-to-run collection of linters and code analyzers, to help validate your source code."
runs:
  using: docker
  image: docker://ghcr.io/step-security/super-linter@sha256:dcb013cf1925323e7ed76fea31ed98145301433cc876473d4a34b058e1193dfe
branding:
  icon: "check-square"
  color: "white"
# You can view https://github.com/step-security/super-linter#environment-variables
# to see a comprehensive list of all environment variables that can be passed
