# Test image for Trivy
FROM alpine:3.24.0@sha256:a2d49ea686c2adfe3c992e47dc3b5e7fa6e6b5055609400dc2acaeb241c829f4

# Add a dummy API token to trigger Trivy secrets detection
ENV GITHUB_API_TOKEN="ghp_aBcDeFgHiJkLmNoPqRsTuVwXyZ1234567890"
